<?php include('elements/nav.html');
include('elements/header.html');
include('elements/bio.html');
include('elements/skills.html');
include('elements/education.html');
include('elements/past_projects.html');
include('elements/work_experience.html');
include('elements/awards.html');
include('elements/call_to_action.html');
include('elements/footer.html');